### ISSUE TITLE
Keyboard help dialog needed

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#102]
From https://github.com/phetsims/density-buoyancy-common/issues/98 and https://github.com/phetsims/buoyancy/issues/76. This should have probably been done over there.

**Comment by zepumph** [comment]
@DianaTavares. I believe the first step here is to make a design. This is because it has custom dragging that likely wants sim-specific wording. For examples you can poke the all our keyboard help dialogs here: https://phetsims.github.io/binder/#joist-KeyboardHelpDialog

**Comment by terracoda** [comment]
@zepumph, that is an amazing link! Thanks for posting it in this issue.

@DianaTavares here are some KBS dialog exmaples that cover draggable objects, sliders, and comboboxes

Gas Properties has all 3 of those:
![Screenshot 2024-04-30 at 15 48 35](https://github.com/phetsims/density-buoyancy-common/assets/1902116/df1f26fb-404a-4934-8410-a7613d1e793e)

**Comment by terracoda** [comment]
It's trivial to change the heading content to be more sim specific. There are other customizations that can be made if they are really important for the interaction or for the organization of the dialog content. For example, is GFL:B and GFL regular, the Move Spheres and Change Mass sections were reduced to just one set of arrow keys even though all the 4 arrow keys work. Doing this emphasizes the orientation of the interaction in GFL:B, and de-clutter the instructions for both sims. De-cluttering was essential for GFL regular because the instructions for grabbing and moving the Ruler are long.

Gravity Force Lab: Basics
![Screenshot 2024-04-30 at 15 55 30](https://github.com/phetsims/density-buoyancy-common/assets/1902116/2138f00c-b5f0-424d-8ee0-94a7d834434f)

Gravity Force Lab (regular)
![Screenshot 2024-04-30 at 15 53 50](https://github.com/phetsims/density-buoyancy-common/assets/1902116/08b80cb6-1b78-43ab-88c5-bad9ac1b44c4)

**Comment by terracoda** [comment]
**Some Tips:**
- Basic Actions always comes last since those are likely known to keyboard users.
- Instructions for the interactions should ideally come in order of importance of the interaction in the sim.
- Instructions are per screen
- If you run out of room (you won't for Density and Buoyancy) you can potentially leave off interactions that have been described on a previous screen's KBS dialog (not ideal, but it has happened).

**Comment by terracoda** [comment]
And here's one last example from Quadrilateral where we changed the language from "Move Draggable Items" to "Move Corners and Sides" and did some more customization as well.
![Screenshot 2024-04-30 at 16 11 21](https://github.com/phetsims/density-buoyancy-common/assets/1902116/3296fb03-6d4e-435b-84f0-51a5fb74a726)

I hope these examples are helpful. Let me know if you need anything else for Keyboard Shortcuts dialogs.

**Comment by DianaTavares** [comment]
Thanks for all your support @terracoda!! 

Buoyancy is super general. Then I use the general picture that @terracoda share and delete the information that is not going to b needed in each screen, this is the information:

**Intro Screen**
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/50ce3d3b-4a73-4797-8413-7b520aebab08)

**All the other Screens**
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/16d6f010-d071-4d64-a3b8-5019a91dfdaf)

**Comment by terracoda** [comment]
@jessegreenberg, I am not sure if "Pop Up Menu" is the final heading for the latest version of combobox. Can you double check that. We just updated the common code combobox info for Gas Properties and I can't remember if "Pop Up Menu" was the final text for the heading.

**Comment by jessegreenberg** [comment]
Yes, "Pop Up Menu" was the choice from https://github.com/phetsims/scenery-phet/issues/852.

**Comment by terracoda** [comment]
Thanks for posting the issue number. In this comment, https://github.com/phetsims/scenery-phet/issues/852#issuecomment-2070237298

I had suggested "Show Choices" or "Pop Open Menu", since the menu doesn't always go up.

And sorry, I am not sure what I am supposed to review in phetsims/scenery-phet/issues/852

**Comment by jessegreenberg** [comment]
Ah, I think just to confirm you like the final language for default content. If you want it to change to "Show Choices", can you please comment over there?

**Comment by terracoda** [comment]
Over in the other issue, I made the default to "Change X" or "Change Choice". That captures the spirit of the heading language better, since "Show Choices" is step 1.

**Comment by samreid** [comment]
@terracoda and I reviewed the implementation and it seems good to close. @terracoda indicated we could change the headings to say e.g., "drag blocks" or things that are more screen-specific, but we discussed that that is non-trivial and could take >1hr to do for all 10 screens across 3 sims. So we are OK to close.
