### ISSUE TITLE
Change fluid selection radio buttons for combo box

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#127]
Today, @zepumph @samreid and I saw that the fluid density radio button panel is a little too crowded, and wouldn't pass the string test. We suggest a bit of a redesign, maybe having two rows of options?

We'll also look into setting better maxWidths for the texts

![Image](https://github.com/phetsims/buoyancy-basics/assets/37052186/d6cfca2f-3bc1-4783-8f7a-1b386ca5884b)

**Comment by zepumph** [comment]
Today during design meeting with @DianaTavares, @samreid @AgustinVallejo @zepumph, we decided that horizontal alignment for text was generally scary for i18n, and we would like to try out using a combo box for these cases (B:B export and Buoyancy Intro). 

I bet we could split `FluidDensityControlNode` into two classes, and use the super class (just the combo box) in these two cases. That is what I did in `MaterialControlNode`

**Comment by DianaTavares** [comment]
This control is then going to change in Buoyancy  (intro screen) and Buoyancy basics (both screens). Please keep in mind that it is going to change the Keyboard Shortcuts Help Dialog, because we are adding a combo box, that mean add this section:

![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/2f0231f6-e784-4cde-b8ac-bd3f7b35de02)

**Comment by DianaTavares** [comment]
It is perfect!!

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
