### ISSUE TITLE
missingStringPhetioElements "density.general.model.strings.densityBuoyancyCommon.averageStringProperty"

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#175]
In https://github.com/phetsims/density-buoyancy-common/issues/153 the averageStringProperty became systemAStringProperty in https://github.com/phetsims/density-buoyancy-common/commit/eecee729de792fc08aecd636a1af31c23f8e87ee. But now the migration wrapper says:

missingStringPhetioElements
"density.general.model.strings.densityBuoyancyCommon.averageStringProperty"

Does density 1.1 use the string `average`? How should we proceed?

**Comment by zepumph** [comment]
Ok. I understand the problem. It is annoying but likely not too troublesome. 

Info:
* `Bottle` is where the "averageString" was used.
* the bottle as a feature is only used in Buoyancy, but it is imported in DensityBuoyancyScreenView here: https://github.com/phetsims/density-buoyancy-common/blob/322fd8d87c3e631f042b736eb54d1dc2cac2d638/js/common/view/DensityBuoyancyScreenView.ts#L510-L552
* That is how the averageString (only used in buoyancy) is published in Density and has been getting translated for Density even though it isn't used. 

To proceed:
* We can just ignore this problem, and don't need to support migration for this. Perhaps with a report processor, or a simple rename or something. 
* That said it is interesting to note how this COULD have been a big issue, because `density-buoyancy-common` is common code, at least as it pertains to translation, in which the available keys to translate are taken from main, not from the DBC sha upon publication. So when this string was deleted, it stopped being served as a string to translate for Density 1.1. This is scary, and I want to make sure that @samreid and @AgustinVallejo understand this nuance, since it is definitely a potential drawback to using the common sim-suite repos. Again. There are no problems here that I'm aware of that need active managing, but to me it seems like a near miss, and it is likely worth investigating to see if we have deleted any other strings that were actually used by density. I'll do that next here.
* Where any other DBC strings used in density 1.1 deleted on main?

**Comment by zepumph** [comment]
>Where any other DBC strings used in density 1.1 deleted on main?

Using this script I found one other problem with `material.cement`.

<details>

```js
const fs = require( 'fs' );
const axios = require( 'axios' );

axios.get( 'https://phet.colorado.edu/sims/html/density/latest/english-string-map.json' ).then( response => {
  const releaseBranchStrings = response.data;
  const raw = fs.readFileSync( '../density-buoyancy-common/density-buoyancy-common-strings_en.json' );
  const mainStrings = JSON.parse( raw );

  const requireJSNamespace = 'DENSITY_BUOYANCY_COMMON/'

  Object.keys( releaseBranchStrings ).forEach( releaseBranchString => {
    if ( releaseBranchString.startsWith( requireJSNamespace ) ) {
      const stringKey = releaseBranchString.replace( requireJSNamespace, '' );
      if ( !mainStrings.hasOwnProperty( stringKey ) ) {
        console.log( 'not found on main: ', stringKey );
      }
    }
  } );
} )

```
</details>

I'll go ahead and add back that string, and we can get rid of it when we publish Density 1.2

**Comment by zepumph** [comment]
@samreid can you think of anything else here?

**Comment by samreid** [comment]
Thanks for reminding me that the strings are taken from main, I forgot about that when advising @AgustinVallejo to rename keys. I'm ready to close the issue, but let's make sure @AgustinVallejo is aware of https://github.com/phetsims/density-buoyancy-common/issues/175#issuecomment-2152948306 first.

**Comment by AgustinVallejo** [comment]
Really interesting read, I double and triple checked that 'Average' was not used in density, because I'm aware of how stringKeys are really sensitive to deletions or changes due to translations. Will be very careful with DBC from now on, thanks! closing
