### ISSUE TITLE
Density C Item on Shapes screen isn't stateful

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#203]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, In Studio/State Wrappers on the Shapes Screen:
If the sim is launched with Density C selected in the combobox, the Standard Wrapper opens showing the word "Custom" instead of "Density C". The color in the pool matches that of Density C. 
I don't see this issue with other liquids.  

**Steps to reproduce**
1. In the State Wrapper, set state rate = 0
2. Go to the Shapes Screen in the upstream sim and change the liquid to Density C. 
3. Press Set State Now. 

**Visuals**
<img width="500" alt="Screenshot 2024-06-13 at 3 46 13 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/a494a51a-89ab-4104-a90a-5bc313512f83">

**Comment by AgustinVallejo** [comment]
Found a solution but wanted to discuss first. The material DENSITY_C has a density of 490 kg/m^3. The slider goes down to 500 kg/m^3 (0.5L). So there's multiple questions for multiple people:
- @samreid @zepumph Do you think it's intentional that when state is set, materials outside the range are marked as custom? Or is this a bug? Couldn't find where this was happening. See the patch below to where this range had to be changed.
- @DianaTavares In case what was mentioned above wasn't a bug, would you rather change DENSITY_C to something above 500 so it works? Or leaving that density at 490 but changing the fluid slider range down to 0.4:

![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/ab6d45c9-51e4-4261-8cab-499c2ecfbb11)

<details>

```diff
Subject: [PATCH] a
---
Index: js/common/view/FluidDensityControlNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/FluidDensityControlNode.ts b/js/common/view/FluidDensityControlNode.ts
--- a/js/common/view/FluidDensityControlNode.ts	(revision 184ffb93ed5425d08d18ed5aed4002cc93e44162)
+++ b/js/common/view/FluidDensityControlNode.ts	(date 1719254145823)
@@ -51,7 +51,7 @@
       titleProperty: DensityBuoyancyCommonStrings.fluidDensityStringProperty,
       valuePatternProperty: DensityBuoyancyCommonConstants.KILOGRAMS_PER_VOLUME_PATTERN_STRING_PROPERTY,
       property: fluidMaterialProperty,
-      range: new Range( 0.5, 15 ),
+      range: new Range( 0.4, 15 ),
       toNumericValue: material => material.density / DensityBuoyancyCommonConstants.LITERS_IN_CUBIC_METER,
       createCustomValue: density => Material.createCustomLiquidMaterial( {
         density: density * DensityBuoyancyCommonConstants.LITERS_IN_CUBIC_METER,

**Comment by DianaTavares** [comment]
I looked in the design document for the reason for the values chosen for the mystery fluids and found a note in the design meeting of May 2019.  I kind of remember that the suggestion was to use a value outside the sliders because some students find the value of mystery by looking for the same behavior of the mystery, but by manipulating the custom (for example, if the mystery density gets a buoyancy force of 19N, then they move the custom density until they get a buoyancy of that value). If the value is outside the range, at least they can know that is smaller, and teachers can ask questions of "How smaller can it be?" these kinds of follow-up questions, and a motivation to use the mathematical models, make graphs to extrapolate data, etc.  

I thought that the density mystery values pointed to real fluids, but now I see that they don't. they are just numbers that I select. Then the importance is not the value, it can be different if needed, but I like the idea of values outside the range of custom.

**Comment by AgustinVallejo** [comment]
Discussed in Slack and we decided to treat it as a bug. Also SR said:
> Maybe it is this code?
https://github.com/phetsims/density-buoyancy-common/blob/4a78e5595349596aac222fdf6efc500648439cb0/js/common/view/ComboNumberControl.ts#L211-L232
called by this?
https://github.com/phetsims/density-buoyancy-common/blob/2b684da7cbb6cddd22489faedad6b2180b7b14cb/js/common/view/FluidDensityControlNode.ts#L56-L59

**Comment by zepumph** [comment]
@AgustinVallejo and I worked on this. The current behavior in Slider.ts is that if the valueProperty changes from something other than the slider, than it is allowed to go outside the range provided to the slider. PhET-iO was breaking that because of an extra call to the rangePropertyObserver due to reference equality with `Range` instances, that is fixed above, and the behavior is now the same for the upstream sim (setting the combo box to change the density valueProperty) as well as the downstream sim( PhET-iO setting the valueProperty).


---------------------------------------

We were a bit curious if this behavior was desirable in general though, and se we asked slack:

>@Agustín Vallejo and I are surprised to see that there is no logic in Slider that asserts that the valueProperty stays inside of the provided range. There is logic ensuring that if you are changing the value via the slider, it will only ever stay within the range. But if something else (like the underlying model) changes the valueProperty, it doesn't error when going outside the range. we were wondering if this was by design. Are there cases that we know and like where we like this current behavior: the valueProperty driving a slider is set well beyond the range of the slider, and the slider just shows the min/max closest to the value?


We'll wait to hear back on that part.

**Comment by zepumph** [comment]
We didn't hear anything. I think we can just proceed without doing anything more.
