### ISSUE TITLE
Are `secondaryMassVisibleProperty` and `secondaryMass.visibleProperty` redundant?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#25]
During code review #5, I saw this code in DensityExploreModel:

```js
    this.secondaryMassVisibleProperty.link( secondaryMassVisible => {
      this.secondaryMass.visibleProperty.value = secondaryMassVisible;
    } );
```

Do we need both properties? If so, please explain how they are different and why it is important to have both.

**Comment by jonathanolson** [comment]
I think this ends up being a phet-io design question. After the recent refactoring to add `visibleProperty` to individual masses, it would simplify the code to rely on the second masses' visibleProperty. @arouinfar thoughts on whether the top-level model Property is helpful or not?

**Comment by arouinfar** [comment]
On the surface, `secondaryMassVisibleProperty` and `secondaryMass.visibleProperty` do seem redundant. However, I think they may be somewhat different. The former is hooked up to the RadioButtonGroup responsible for toggling between one and two blocks, for example `density.exploreScreen.view.secondMassVisibleControl`. In contrast, changing the state of `secondaryMass.visibleProperty` does not change the state of the RadioButtonGroup. The 2nd block could be hidden while its corresponding control panel is visible (if `twoBlocksRadioButton` is selected).

In Density and Buoyancy, there are some screens where there are several blocks always present in the play area, such as `density.mysteryScreen` or `buoyancy.introScreen`, and other screens where there is a radio button to toggle between either one or two blocks, such as `density.exploreScreen` and `buoyancy.exploreScreen`. From a design perspective, it seems cleanest if each block could have its own `visibleProperty`. 

Would it be possible/reasonable to hook up the one vs. two block RadioButtonGroup to `secondaryMass.visibleProperty` instead of `secondaryMassVisibleProperty`?

**Comment by arouinfar** [comment]
Tagging https://github.com/phetsims/density/issues/76 since it's relevant to the PhET-iO design review.

**Comment by jonathanolson** [comment]
Handled this for everything except Buoyancy's Shapes screen (which will probably need phet-io design on its own).

@arouinfar how does this look?

@samreid does this satisfy your concern?

**Comment by samreid** [comment]
Yes, the code change looks good.  @arouinfar please close if the design is satisfactory.

**Comment by arouinfar** [comment]
Looks good to me, thanks @jonathanolson
