### ISSUE TITLE
Factor out the `cameraLookAt` values

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#27]
During code review #5, I noticed these `cameraLookAt` values:

![image](https://user-images.githubusercontent.com/679486/128901313-ba9406f0-f793-48f5-97b9-9bdeac5c97fb.png)

Is it a general pattern that density screens look at 0,0,0 and buoyancy screens look at 0, -0.18, 0?  Can those be factored out to a base ScreenView class?  Is the default of 0, -0.1,0 ever used?

**Comment by jonathanolson** [comment]
It does look like `BuoyancyIntroScreenView` uses the default. A supertype doesn't make sense to me for this level, since we have changed individual screens' values in the past, and are likely to do so with Buoyancy. How about I factor out used values into DensityBuoyancyCommonConstants? I wouldn't WANT to refactor things to make it a config instead of options, but I'd probably want to specify it individually for every screen.

Thoughts?

**Comment by jonathanolson** [comment]
Done above, can you review?

**Comment by samreid** [comment]
Was the change in DensityBuoyancyScreenView intended to be a pure refactor?  The value changed from -0.1 to 0.

**Comment by jonathanolson** [comment]
> Was the change in DensityBuoyancyScreenView intended to be a pure refactor? The value changed from -0.1 to 0.

Yes, I moved the one usage of that value out to the screen that is using it, so the default isn't being used currently.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
