### ISSUE TITLE
Should the first publication of Buoyancy be 1.2 to match Density 1.2?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#338]
Today @AgustinVallejo @zepumph and I asked whether the first publication of Buoyancy should be 1.2 so that it will be synchronized with the entire suite?  We found this after looking at: https://github.com/phetsims/density/issues/200

For our users, maybe it would be nice to see Buoyancy 1.0 is the first one. But for PhET developers and PhET-iO clients/developers it would be clearer to synchronize.  Also, many users may just ignore the version number. For instance, it would be difficult to imagine a user not wanting to use Buoyancy because it is 1.2 instead of 1.0.

**Comment by arouinfar** [comment]
It makes a lot of sense for all of the sims in the suite to have the same version (at least for major/minor). I like the idea of bumping Buoyancy up to 1.2 for its first release. I'm pretty sure we've done something similar in other sim suites, but I can't recall which sim(s) off the top of my head.

> For our users, maybe it would be nice to see Buoyancy 1.0 is the first one.

I'd wager that most users are unaware of what version they use for most software, and are unlikely to care. We don't forefront version info. URL paths use `/latest/` and email announcements never include version info, either.

**Comment by samreid** [comment]
Good idea @zepumph, and I agree with your reasoning @arouinfar. I updated the buoyancy and buoyancy-basics package.json version to match density. @zepumph anything else to do here?

**Comment by samreid** [comment]
@zepumph recommends publishing a dev version of all 3 so they are matched up. After that, the issue can be closed.

**Comment by samreid** [comment]
Deployed: https://phet-dev.colorado.edu/html/density/1.2.0-dev.3/phet/density_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/density/1.2.0-dev.3/phet-io/

Deployed: https://phet-dev.colorado.edu/html/buoyancy/1.2.0-dev.3/phet/buoyancy_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/buoyancy/1.2.0-dev.3/phet-io/

Deployed: https://phet-dev.colorado.edu/html/buoyancy-basics/1.2.0-dev.3/phet/buoyancy-basics_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/buoyancy-basics/1.2.0-dev.3/phet-io/

**Comment by samreid** [comment]
CT shows this message: `[CONSOLE] Update check failure: simulation buoyancy not found`

due to this code:

```ts
    /**
     * @returns {boolean}
     * @public
     * @ignore - not needed by PhET-iO Clients
     */
    get isSimNotPublished() {
      return this.major < 1 || // e.g. 0.0.0-dev.1
             ( this.major === 1 && // e.g. 1.0.0-dev.1
               this.minor === 0 &&
               this.maintenance === 0 &&
               this.testType );
    }

    /**
     * @returns {boolean}
     * @public
     * @ignore - not needed by PhET-iO Clients
     */
    get isSimPublished() {
      return !this.isSimNotPublished;
    }
```

Are there other parts in the pipeline that assume 1.2 has prior publications? Is this safe to ignore, or how should we proceed?

**Comment by zepumph** [comment]
I believe we should give up, and not do this update (publishing buoyancy as 1.0). But first can we double check on this at dev meeting? Perhaps others have opinions about how to handle this kind of thing.

**Comment by zepumph** [comment]
From dev meeting today, it would be pretty nice to maintain these all with the same versioning. Let's try to power through some of the above problems, and see if it is feasible. To double check:

- [x] No hard error in the migration wrapper (should just not load a previous version because 1.1 doesn't exist. Similar to if loading 1.0
- [ ] The above error with simVersion. Do we assume things? Should we just not log that trouble?

**Comment by zepumph** [comment]
In this block here that is responsible for logging the error that https://github.com/phetsims/density-buoyancy-common/issues/338#issuecomment-2288595705 shows:

https://github.com/phetsims/joist/blob/12822fe09a5b8bb3a7d9a89cfbbf00199e8c0f86/js/updateCheck.ts#L109-L110

I feel like it would be nice to see if our "error" case: `simulation buoyancy not found` was an "up to date" case, because the previous version was not found, but to know that, I would have to have a look at the logic of the website service. 


Gotcha! https://github.com/phetsims/website/blob/main/src/java/edu/colorado/phet/website/services/CheckHTMLUpdates.java#L24

**Comment by zepumph** [comment]
Ok, after reviewing the above. I don't think we are going to have any problems here. The error being logged right now is just because we are now pinging the server for info about buoyancy, which it doesn't have. We cannot do a local check because that just checks on 1.0. Once we publish to production, then there will be an entry in the database, and we will successfully be noted as up to date. I'm ready to close this issue. Thanks all!
