### ISSUE TITLE
block material combo box says "custom" no matter which option is chosen [BASICS]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#362]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1136 and Buoyancy Basics:
On the Explore screen, changing the block material of Block A and Block B results in the block appearing white and the combobox saying 'custom'.
As I go through all of the material options, I can see that the density is changing, even though the appearance of the block isn't. 

I don't see this issue in Buoyancy or Density. 

**Steps to reproduce**
1. In Buoyancy Basics on the Explore Screen, change the material of either (or both blocks) in the combo box from 'wood' to anything else. 
2. Continue to move through all the options

**Visuals**

https://github.com/user-attachments/assets/eccaad44-f1da-4ae1-8fee-03b48bd172cc

**Comment by zepumph** [comment]
Taking a look now.

**Comment by zepumph** [comment]
This chunk has regressed, and isn't appropriately being locked out during combo box control:

https://github.com/phetsims/density-buoyancy-common/blob/f8d98aac6694d1bf4a5f583ab36a8775d5f157a8/js/common/view/BlockControlNode.ts#L44-L51

**Comment by zepumph** [comment]
Present in 1.2.0-dev.3 from 8/13

**Comment by zepumph** [comment]
Looks like we just had two copies of the same code:

https://github.com/phetsims/density-buoyancy-common/blob/5cfe1bd79530526f4608c3440f3fda5c2bf5d850/js/common/model/MappedWrappedProperty.ts#L44-L62

And each didn't lock the other listener, so this has been broken since our larger material refactor back in July. @samreid does this seem reasonable to you?

One thing I wanted to check on is how this behavior is now for all MaterialProperties. For PhET-iO, if you set the custom density to a desired value, when the student changes from custom -> wood -> custom then the density will be back to the wood value. This is for all combo boxes that have a custom option. Should we care about this? Perhaps the correct way to alter something like this is through the global materials, like the mystery ones?

**Comment by samreid** [comment]
I think it is a good question to discuss with a designer. I thought there was a precedent where switching to custom is supposed to preserve the same value, but I'm not sure what special case that was, or if it is supposed to be everywhere.  It could be confusing if that behavior is only under special circumstances.

I think consistency would be more important, and since I don't recall the case where a value is supposed to copy over to density, I'm not sure how to proceed.

The current behavior is consistent, and explainable. We could document it in implementation-notes.md or examples.md. Or check with @DianaTavares?

**Comment by zepumph** [comment]
The primary bug is that if you set a custom density in any UI that changes the custom density (mass/volume block control, B:B block density slider, gravity control, fluid density control), then switch away to another material, and then back to custom, it keeps the density from the non custom materials you just came from (like wood). Even on the Density Mystery screen where you can use PhET-iO to customize the density for the custom material.

@samreid and I discussed, and think that most likely we don't want this behavior at all, and all UI components that can alter density should have their own Property, instead of using the `customMaterial.densityProperty` and overwriting that value with the current material's density (like wood). 


Before proceeding with this larger  but likely necessary change, we want to touch base with designers.

**Comment by DianaTavares** [comment]
Let's discuss it tomorrow! After stand-up, I have a meeting, then, I can after 11 am. Please check my calendar to find an available spot! I am a little worried that is @arouinfar the designer expert in PhET-iO, but I hope that with my knowledge and the examples that Amy already wrote, we can see the effect of the proposed change.

**Comment by zepumph** [comment]
Today during design meeting, we agreed that the current behavior is acceptable. We think of custom as a "mode" instead of a "value", and so when you switch to custom, the custom density value will change to whatever the previous material density was, like wood/water (but not for mystery so it doesn't give away the answer).

**Comment by zepumph** [comment]
Closing
