### ISSUE TITLE
Changes to examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#371]
For https://github.com/phetsims/qa/issues/1136

For Buoyancy Basics under Reorder the materials in the ComboBox change
`buoyancyBasics.exploreScreen.view.fluidDensityPanel.comboBox.listBox`

to 
`buoyancyBasics.exploreScreen.view.fluidPanel.comboBox.listBox`

Any further changes/suggestions will also be added to this issue.

**Comment by Nancy-Salpepi** [comment]
For Density, since the Volume Units are the only thing in the Simulation Tab of the Preferences Menu I would suggest changing the visible property of the the tab rather than the visible property of the volumeUnits Control. 

Change:
`density.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.volumeUnitsControl.visibleProperty`

To:
`density.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.simulationTab.visibleProperty`

**Comment by zepumph** [comment]
- [x] Please note that we should update some doc here about how "custom" materials works as a mode instead of a value, https://github.com/phetsims/density-buoyancy-common/issues/362#issuecomment-2321825938

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi! I made the suggested changes in the above commits. 

To address https://github.com/phetsims/density-buoyancy-common/issues/371#issuecomment-2321827122, I added this to the Density and Buoyancy under the 'Specify block density' section:
> The Custom material behaves differently, allowing independent control of mass and volume. Its `densityProperty` is not a constant, and can be changed by subsequent interaction with the mass, volume, or material controls. For this reason, we recommend you first set the material to ‘Custom’ before modifying its density.

I did not add this information to Buoyancy: Basics, because `customMaterial.densityProperty` behaves a bit differently since it is tied to the Density slider.

Closing!
