### ISSUE TITLE
Density panel can change size slightly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#375]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1136, on the Intro Screen of the Density simulation, when either block's density reaches  the max value (10.00), the text gets smaller which causes the density accordion box to get smaller. This doesn't happen in published. 
 
**Steps to reproduce**
Here is an example:
1. In the Density sim, on the Intro screen, change Block A to custom
2. Increase the Mass to max amount
3. Move the Volume slider back and forth between min and max 

**Visuals**

https://github.com/user-attachments/assets/aa5f5574-3f0d-440b-a290-0ef5fd235d71

**Comment by samreid** [comment]
At the given font size, the maxWidth was already shrinking things, so that accentuated the shrinking when it got the extra decimal point for 10.0.  So I adjusted the font and maxWidth to try to keep it as similar as possible but without the resizing. There is a bit more boundary around the edge due to this. I tested in density intro screen. @Nancy-Salpepi can you please test on phettest?

**Comment by Nancy-Salpepi** [comment]
Looks great now Sam. Closing!
