### ISSUE TITLE
Overlap of block labels when units are long

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#38]
From #5, I tried "kilograms" instead of "kg" and there was some overlap.  Should there be a maxWidth?

![image](https://user-images.githubusercontent.com/679486/128961011-bc16349e-b42e-4873-890f-d7a79c396655.png)

**Comment by jonathanolson** [comment]
@DianaTavares presumably there should be a maxWidth here, any thoughts on whether we want the English variant to scale down at all? I could try to find the width it takes in common browsers, and set a maxWidth a bit above that.

**Comment by DianaTavares** [comment]
In all the sims we allow to translate the units, then this should be the case here too. I think that the maxWidth can not be much more longer because we can have the problem related to this issue: https://github.com/phetsims/density/issues/64 where the labels of small blocks overlap. 

![image](https://user-images.githubusercontent.com/26031501/129213607-1a95713c-f71c-4b2e-a40f-94dc00bdf5ad.png)

I like your suggestion of looking in common browsers. And I think that if the solution makes that small blocks cover the units, it is ok!

**Comment by jonathanolson** [comment]
Added the maxWidth above, @DianaTavares can you verify?

**Comment by DianaTavares** [comment]
working!
