### ISSUE TITLE
Moving pointer causes keyboard focus highlight to disappear

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#393]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1141, when a control or object has keyboard focus, moving the pointer causes the highlight to disappear even though it still has keyboard focus. I don't see this behavior in other recently published sims (MSaB, FEL, PDL, BaN, CaV). In those sims, the focus highlight doesn't disappear until I click on the screen. 

This can lead to odd scenes where a block appears to be defying gravity. 

**Steps to reproduce**
1. In Density on the Intro screen, tab to and grab Block A.
2. Move Block A above pool
3. Move the pointer across the screen
4. Press left/right arrow keys--highlight returns
5. Tab to Material combo box
6. Move pointer
7. Press space or enter

**Visuals**

https://github.com/user-attachments/assets/cc8b22fb-21db-4a3a-9933-f871025347ea

**Comment by zepumph** [comment]
This is expected behavior that occurs from the interactive highlight system. If you are experiencing this behavior when you DO NOT have interactive highlights enabled, then there may be a bug, but otherwise, this is logic that hides the focus highlight and turns on the interactive highlights when you move/use the mouse enough. 

https://github.com/phetsims/joist/blob/084b04e87cf07445a11a0c7915984617795ddad1/js/HighlightVisibilityController.ts#L123-L144

>. I don't see this behavior in other recently published sims (MSaB, FEL, PDL, BaN, CaV)

I saw similar behavior on startup (no amount of mouse moving would hide the focus highlight), but when I turned on Interactive Highlights, I had the same exact behavior as the above video.

I don't believe that this is perfect, but it probably won't get worked on further until we have more sole time to devote to https://github.com/phetsims/joist/issues/750.

@Nancy-Salpepi please feel free to close unless you had this behavior when interactive highlights were not on.

**Comment by Nancy-Salpepi** [comment]
I apologize Michael. I thought I had tested with them off as well but I guess I didn't. 
Closing.

**Comment by zepumph** [comment]
Please no need to apologize! This stuff is much too complicated.
