### ISSUE TITLE
Screenshots for all three sims

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#422]
While starting to publish to production, @samreid and I saw that screenshots need creating. @KatieWoe does QA normally do this step? I'm happy to help just point me in the right direction.

**Comment by KatieWoe** [comment]
Either QA or the designers usually do it. @DianaTavares do you have any preferences?

**Comment by zepumph** [comment]
Looks like @arouinfar volunteered in slack.

**Comment by KatieWoe** [comment]
Sounds good. I'm willing to help if needed @arouinfar

**Comment by arouinfar** [comment]
@zepumph @samreid I created screenshots for Buoyancy and Buoyancy: Basics and added them to main and 1.2 in the commits above. The website has a limit of 4 screenshots per sim, so I decided to leave out the Compare screen of Buoyancy. 

@DianaTavares if you want to make any changes to the screenshots, we can do that later. This issue was blocking the publication of the suite, so I decided to go ahead and commit something. 

@KatieWoe for the sake of time, I did not take the screen-specific screenshots because they are not yet being used anywhere. Can you please take care of those for Buoyancy and Buoyancy: Basics? A quick overview in case you're rusty:
1. Set  your viewport sizer to 1536x1008 px
2. Run the sim with `screens` and recreate the situations in the screenshots I just committed, with the exceptions noted in (3) and (4) below.
3. For Buoyancy: Basics, refer to the main screenshot and alt2. 
4. For Buoyancy -- Compare, create any scenario you'd like
5. Follow the `sim-name-screenshot-screenX.png` naming convention, where `X` is the screen number.

**Comment by arouinfar** [comment]
We decided not to retake the Density screenshots because there haven't been any significant visual changes to the sim since the 1.1 release.

**Comment by Nancy-Salpepi** [comment]
@KatieWoe screenshots are ready for commits. Here are the folders:

https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/EnC66i_n1rlGmU8BI6luzXYB-_fAnllZTBLhVyTCv2Ef-w?email=Kathryn.Woessner%40Colorado.EDU&e=EtqYuD

https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/EhK7Ppwtg05Iuy8zg73-XZMBQ3hgA88uyEUqAeR3dBKGvg?email=Kathryn.Woessner%40Colorado.EDU&e=a3YIVe

**Comment by KatieWoe** [comment]
Commits above. Thanks @Nancy-Salpepi for taking the screenshots. @arouinfar everything look good?

**Comment by arouinfar** [comment]
Thanks @KatieWoe @Nancy-Salpepi. Looks like something went wrong with the commits. The screenshots all appear to be 0 bytes, and the commits show an "invalid image source" warning when you click on them.

![image](https://github.com/user-attachments/assets/5f2ba935-e879-4a3b-82f2-d45b76bcc0ec)

![image](https://github.com/user-attachments/assets/8300ef76-4e76-4f2c-9313-4cb95ec35a23)

I tried accessing the files in the links @Nancy-Salpepi shared in https://github.com/phetsims/density-buoyancy-common/issues/422#issuecomment-2402833042, but I don't have access.

If you attach the images to this issue, I can download and commit them.

**Comment by KatieWoe** [comment]
![buoyancy-screenshot-screen2](https://github.com/user-attachments/assets/77b80b9a-d42a-43d7-8816-2e716c80c400)
![buoyancy-screenshot-screen3](https://github.com/user-attachments/assets/be453de4-a1c8-4be8-ac80-b185633553d0)
![buoyancy-screenshot-screen4](https://github.com/user-attachments/assets/502165a8-e0a9-4ffa-abc9-7feb581536ab)
![buoyancy-screenshot-screen5](https://github.com/user-attachments/assets/16455371-4724-4aa4-880e-e1fd5f1ebed6)
![buoyancy-screenshot-screen1](https://github.com/user-attachments/assets/70b04d71-4c9d-4150-a703-ba7882f47f03)
![buoyancy-basics-screenshot-screen1](https://github.com/user-attachments/assets/04bb9673-1b11-4233-84f6-0f84b88549e7)
![buoyancy-basics-screenshot-screen2](https://github.com/user-attachments/assets/488f8441-53ed-4a88-a0a2-b0a8edeed40d)

**Comment by KatieWoe** [comment]
I'm sorry. I'm not sure how that happened.

**Comment by arouinfar** [comment]
No worries, @KatieWoe. Thanks for uploading the screenshots. I committed them above, and everything appears to have worked this time.

There's nothing else to do here, closing.
