### ISSUE TITLE
Customized block colors are not restored in studio "Preview Sim"

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#68]
A client pointed out that Customized block colors are not restored in studio "Preview Sim".  I'm not sure if the problem is sim-specific or phet-io specific, so I've assigned @jonathanolson and myself and @zepumph for now.

**Comment by zepumph** [comment]
This Property is marked as phetioState:false, not sure why. https://github.com/phetsims/density-buoyancy-common/blob/3c4c5d52ebf111f9f5da233572943d37971b30f0/js/common/model/Mass.js#L227

**Comment by samreid** [comment]
It seems like those values should be `phetioState: true`.  I tried changing `phetioState` to true for the material and color properties (and even the custom density property), but it did not solve the problem.  I recommend @jonathanolson take the lead on this issue and reach out to @zepumph or myself as necessary.  There are many parts of Mass.js (including materials, colors, locks, etc.) that may be correlated with this problem.

**Comment by jonathanolson** [comment]
Looking into it. @arouinfar do you know whether we should have things like customColorProperty also saved in the state (so that it could be recustomized?)

**Comment by jonathanolson** [comment]
I believe this is handled, @arouinfar can you verify?

**Comment by arouinfar** [comment]
@jonathanolson the `customColorProperty` is now stateful in master.

@kathy-phet and I are concerned by @samreid's https://github.com/phetsims/density-buoyancy-common/issues/68#issuecomment-1005900825 about `phetioState`. It looks like there are several properties that are `phetioState: false` including `materialEnumProperty`, `customDensityProperty` and `massProperty`.

While these properties are only customizable through the API, they should still be stateful. Students need to be able to submit their state, and if the customizations weren't stateful, their transmitted state won't be accurate.

**Comment by jonathanolson** [comment]
Applied to master and the release branch.

`massProperty` is effectively a derived Property that we changed so that it could be set. There is no advantage in my eyes for it being `phetioState: true`, since when the sim is loaded, `massProperty` will automatically take the correct (same) value that was in the previous saved sim's "state".

**Comment by jonathanolson** [comment]
I believe the rest of the work should be done here.

**Comment by arouinfar** [comment]
Thanks @jonathanolson. The `materialEnumProperty` looks good in master and its state is properly restored when previewing customizations in Studio. Looks like `customDenistyProperty` is `phetioState: true` in Studio, though I don't have a way of verifying the statefulness of customizations, so that'll have to do for now.

**Comment by KatieWoe** [comment]
This looks good in rc.3 from what I can tell. The only oddity I saw was in the random blocks. If you change a block color, and then get a new random set, a new random color is selected. This doesn't seem like a problem to me, but I wanted to check.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I think this behavior is to be expected and reasonable, so I'll go ahead and close.
