### ISSUE TITLE
Address `strictAxonDependencies: false`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/density-buoyancy-common#85]
For https://github.com/phetsims/axon/issues/441, @samreid added 3 occurrences of `strictAxonDependencies: false` to this repo. They should be inspected/addressed when this repo is worked on.

**Comment by zepumph** [comment]
I removed these usages and tested with local fuzzing in buoyancy and density. After an hour of fuzzing, I couldn't reproduce the problems. These usages are all DerivedProperty that listen to boundsProperties. My best guess is that the problem was upstream of these cases, and another fix solved this one too, but I'm just going to check back in on CT to see if I can get hints about how to reproduce this.

**Comment by samreid** [comment]
Based on https://github.com/phetsims/faradays-electromagnetic-lab/issues/57 I wonder if some class of failures are triggered by ?listenerOrder=reverse.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/faradays-electromagnetic-lab/issues/65 we deemed it appropriate to use this workaround to get around listing to the `visibleBoundsProperty` (since that cascaded deep into scenery, effecting things like fill/stroke Properties in children). We will likely run into this again, but I don't feel like we have enough cases to warrant further investigation.
